# infrastructure/db/docker-compose.yml
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: hushstore_sqlserver_dev
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver_data:
    name: hushstore_sqlserver_data